---

- hosts: all
  become: yes
  tasks:
    - apt: update_cache=yes
    - apt: name=apache2
    - apt: name=php5
    - apt: name=mysql-server
    - apt: name=python-mysqldb
    - apt: name=zip
    - mysql_user: name=wordpress password=wordpress priv=*.*:ALL login_user=root
    - mysql_db: name=wordpress login_user=root
    - get_url: url=https://de.wordpress.org/latest-de_DE.zip dest=/var/www/html
    - unarchive: src=/var/www/html/wordpress-4.5.3-de_DE.zip dest=/var/www/html/ copy=no
