# ansible-roles/lamp/tasks/main.yml
---
- name: merge php config
  set_fact:
    merged: "{{ general_config|union(config) }}"
- name: install packages
  apt: name={{ item }}
  with_items: "{{ general_packages }}"
- name: write php config for apache
  ini_file: dest=/etc/php5/apache2/php.ini
            section={{ item.section }}
            option={{ item.option }}
            value={{ item.value }}
  with_items: "{{ merged }}"
  notify: reload apache
